#!/usr/bin/env bash

BAZAAR_APPID="io.github.kolunmi.Bazaar"

if ! flatpak list --system --app --columns=app | grep -Eq "^${BAZAAR_APPID}$"; then
  notify-send -u critical -a Bazaar -i "settings-configure-symbolic" "Bazaar does not seem to be installed, installing it in the background."

  flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  echo "Installing Bazaar..."
  flatpak install --system -y "${BAZAAR_APPID}"

else
  notify-send -u normal -a Bazaar -i "emblem-default-symbolic" "Bazaar is already installed. Launching now..."
fi

flatpak run "${BAZAAR_APPID}" "$@"
